import time
from selenium import webdriver


names = [
    # "samara.justconnect",
         # "samara.justconnect.comments",
         # "samara.justconnect.commentsprivacy/",
         # "samara.justconnect./crm/",
         # "samara.justconnect/district",
         # "samara.justconnect/home",
         # "samara.justconnect/news/",
         # "samara.justconnect/p/megafon/",
         # "samara.justconnect/p/megafon/about/",
         # "samara.justconnect/p/megafon/paket/",
         # "samara.justconnect/po-adresu/",
         # "samara.justconnect/registration/",
         # "samara.justconnect.ru/rejting-provajderov/",
         # "samara.justconnect.ru/s/office/",
         # "samara.justconnect.ru/s/private/",
         # "samara.justconnect.ru/speed_test/"
         # "samara.justconnect.ru/street1",
         # "samara.justconnect.ru/street2",
         # "samara.justconnect.ru/tarifs/",
         # "samara.justconnect.ru/tarifs1",
         # "samara.justconnect.ru/tarifs2",
         # "samara.justconnect.ru/tarifs3",
         # "samara.justconnect.ru/tarifs4",
         # "samara.justconnect.ru/tarifs5",
         # "samara.justconnect.ru/tarifs6",
         # "samara.justconnect.ru/tarifs7",
         # "samara.justconnect.ru/tarifs8",
         # "samara.justconnect.ru/tarifs9",
         # "samara.justconnect.ru/tarifs10",
         # "samara.justconnect.ru/tarifs11",
         # "samara.justconnect.ru/tarifs/megafon",
         # "dominternet.ru/",
         # "dominternet.ru/about/",
         # "dominternet.ru/blog/",
         # "dominternet.ru/career/",
         # "dominternet.ru/compare/",
         # "dominternet.ru/contacts/",
         # "dominternet.ru/downdetector/",
         # "dominternet.ru/kaliningrad/kashtanovayaalleya/",
         # "dominternet.ru/kaliningrad/providers",
         # "dominternet.ru/legal/privacy/",
         # "dominternet.ru/legal/termsofuse/",
         # "dominternet.ru/locations/",
         # "dominternet.ru/novosibirsk/forhouse/",
         # "dominternet.ru/novosibirsk/providerstoaddress/",
         # "dominternet.ru/novosibirsk/providers/",
         # "dominternet.ru/novosibirsk/providers1",
         # "dominternet.ru/novosibirsk/providers2",
         # "dominternet.ru/novosibirsk/providers3",
         # "dominternet.ru/novosibirsk/providers4",
         # "dominternet.ru/novosibirsk/providers5",
         # "dominternet.ru/novosibirsk/providers/rostelecom/",
         # "dominternet.ru/novosibirsk/providers/rostelecom1",
         # "dominternet.ru/novosibirsk/providers/rostelecom2",
         # "dominternet.ru/novosibirsk/providers/rostelecom3",
         # "dominternet.ru/novosibirsk/providers/rostelecom4",
         # "dominternet.ru/novosibirsk/providers/rostelecom5",
         # "dominternet.ru/novosibirsk/providers/rostelecom6",
         # "dominternet.ru/novosibirsk/providers/rostelecom7",
         # "dominternet.ru/novosibirsk/providers/rostelecom8",
         # "dominternet.ru/novosibirsk/providers/rostelecom9",
         # "dominternet.ru/novosibirsk/providers/rostelecom10",
         # "dominternet.ru/novosibirsk/rating/",
         # "dominternet.ru/novosibirsk/reviews/",
         # "dominternet.ru/novosibirsk/tariffs/",
         # "dominternet.ru/novosibirsk/tariffs/100mbit/",
         # "dominternet.ru/novosibirsk/tariffs/1gbit/",
         # "dominternet.ru/novosibirsk/tariffs/200mbit/",
         # "dominternet.ru/novosibirsk/tariffs/300mbit/",
         # "dominternet.ru/novosibirsk/tariffs/500mbit/",
         # "dominternet.ru/novosibirsk/tariffs2",
         # "dominternet.ru/novosibirsk/tariffs/cheap/",
         # "dominternet.ru/novosibirsk/tariffs/fast/",
         # "dominternet.ru/novosibirsk/tariffs/free_connection/",
         # "dominternet.ru/novosibirsk/tariffs/gaming/",
         # "dominternet.ru/novosibirsk/tariffs/internet_mobile/",
         # "dominternet.ru/novosibirsk/tariffs/internet_tv_mobile/",
         # "dominternet.ru/novosibirsk/tariffs/internet-tv/",
         # "dominternet.ru/novosibirsk/tariffs/internet/",
         # "dominternet.ru/novosibirsk/tariffs/promo/",
         # "dominternet.ru/novosibirsk/tariffs/today/",
         # "dominternet.ru/novosibirsk/tariffs/wifi/",
         # "dominternet.ru/novosibirsk/tariffs/with-tv/",
         # "dominternet.ru/providers/rostelecom/",
         # "dominternet.ru/providers/rostelecom/checkaddress/",
         # "dominternet.ru/saratov/",
         # "dominternet.ru/speedtest/",
         # "dominternet.ru/subscriptions/",
         # "gigaboom.ru/",
         # "gigaboom.ru/articles/",
         # "gigaboom.ru/internet4",
         # "gigaboom.ru/internet3",
         # "gigaboom.ru/internet2",
         # "gigaboom.ru/internet1",
         # "gigaboom.ru/office/",
         # "gigaboom.ru/personal-data/",
         # "gigaboom.ru/providers/",
         # "gigaboom.ru/providers/mts/",
         # "gigaboom.ru/providers/mts/reviews/",
         # "gigaboom.ru/providers/mts/sale/",
         # "gigaboom.ru/providers/mts/tariffs/",
         # "gigaboom.ru/rating/",
         # "gigaboom.ru/speedtest/",
         # "gigaboom.ru/tariffs/",
         # "gigaboom.ru/tariffs/besprovodnojinternet/",
         # "gigaboom.ru/tariffs/bezlimitnyetarify/",
         # "gigaboom.ru/tariffs/internet1gbitsek/",
         # "gigaboom.ru/tariffs/internet10mbitsek/",
         # "gigaboom.ru/tariffs/internet100mbit",
         # "gigaboom.ru/tariffs/internet200mbit",
         # "gigaboom.ru/tariffs/internet300mbit",
         # "gigaboom.ru/tariffs/internet400mbitsek/",
         # "gigaboom.ru/tariffs/internet50mbitsek/",
         # "gigaboom.ru/tariffs/internet500mbitsek/",
         # "gigaboom.ru/tariffs/internet800mbitsek/",
         # "gigaboom.ru/tariffs/internetdo300rub/",
         # "gigaboom.ru/tariffs/internetdo500rub/",
         # "gigaboom.ru/tariffs/internetdo800rub/",
         # "gigaboom.ru/tariffs/internettelevidenie/",
         # "gigaboom.ru/tariffs/mobilnyjinternet/",
         # "gigaboom.ru/tariffs/mts",
         # "gigaboom.ru/tariffs/nedorogoj1",
         # "gigaboom.ru/tariffs/provodnojinternet/",
         # "gigaboom.ru/tariffs/skorostnoj",
         # "gigaboom.ru/tariffs/televidenie/",
         # "gigaboom.ru/tariffs/vygodnye",
         # "gigaboom.ru/tariffs/wifi",
         # "gigaboom/terms_of_use/",
         # "internet.gdeluchshe/",
         # "gdeluchshe/company/",
         # "internet.gdeluchshe/domashnijinternet/",
         # "internet.gdeluchshe/internettvmobile/",
         # "internet.gdeluchshe/internetmobile/",
         # "telecom.gdeluchshe/",
         # "internet.gdeluchshe/internetnadachu/",
         # "internet.gdeluchshe/interaktivnoe-tv/",
         # "internet.gdeluchshe/provider/",
         # "internet.gdeluchshe/tariffs/",
         "internet.gdeluchshe/help/",
         "kaliningrad.gdeluchshe/provaidery",
         "kaliningrad.gdeluchshe/provider/rostelekom/"
         ]

urls = [
    # "https://samara.justconnect.ru/",
        # "https://samara.justconnect.ru/comments/",
        # "https://samara.justconnect.ru/comments/privacy/",
        # "https://samara.justconnect.ru/crm/",
        # "https://samara.justconnect.ru/district/%D1%80%D0%B0%D0%B9%D0%BE%D0%BD+%D0%96%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D0%BD%D1%8B%D0%B9/#/tpl=tarifs&price=1200&speed=10&sort=rating",
        # "https://samara.justconnect.ru/home/%D1%83%D0%BB.+%D0%94%D1%8B%D0%B1%D0%B5%D0%BD%D0%BA%D0%BE-id19201-4/#/tpl=tarifs&price=1200&speed=10&sort=rating",
        # "https://samara.justconnect.ru/news/",
        # "https://samara.justconnect.ru/p/megafon/",
        # "https://samara.justconnect.ru/p/megafon/about/",
        # "https://samara.justconnect.ru/p/megafon/paket/",
        # "https://samara.justconnect.ru/po-adresu/",
        # "https://samara.justconnect.ru/registration/",
        # "https://samara.justconnect.ru/rejting-provajderov/",
        # "https://samara.justconnect.ru/s/office/",
        # "https://samara.justconnect.ru/s/private/",
        # "https://samara.justconnect.ru/speed_test/"
        # "https://samara.justconnect.ru/street/#/tpl=tarifs&sort=undefined",
        # "https://samara.justconnect.ru/street/19664/#/tpl=tarifs&price=3100&speed=10&sort=rating",
        # "https://samara.justconnect.ru/tarifs/",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet&price=1200&speed=10&sort=low_cost",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet&price=1200&speed=100&sort=rating",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet&price=1200&speed=1000&sort=rating",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet&price=1200&speed=200&sort=rating",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet&price=1200&speed=300&sort=rating",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet&price=1200&speed=500&sort=rating",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet,router&price=1200&speed=10&sort=rating",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet,tv&price=1200&speed=10&sort=rating",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&benefits=internet,tv,sim&price=1200&speed=10&sort=rating",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&price=1200&speed=10&sort=fast",
        # "https://samara.justconnect.ru/tarifs/#/tpl=tarifs&price=1200&speed=10&sort=low_cost",
        # "https://samara.justconnect.ru/tarifs/megafon/#/tpl=provider_tarifs&provider=1910&price=1200&speed=10&sort=rating",
        # "https://dominternet.ru/",
        # "https://dominternet.ru/about/",
        # "https://dominternet.ru/blog/",
        # "https://dominternet.ru/career/",
        # "https://dominternet.ru/compare/",
        # "https://dominternet.ru/contacts/",
        # "https://dominternet.ru/downdetector/",
        # "https://dominternet.ru/kaliningrad/kashtanovaya-alleya/",
        # "https://dominternet.ru/kaliningrad/providers-not-found/?houseUrl=@/aMGBTw",
        # "https://dominternet.ru/legal/privacy/",
        # "https://dominternet.ru/legal/terms-of-use/",
        # "https://dominternet.ru/locations/",
        # "https://dominternet.ru/novosibirsk/for-house/",
        # "https://dominternet.ru/novosibirsk/providers-to-address/",
        # "https://dominternet.ru/novosibirsk/providers/",
        # "https://dominternet.ru/novosibirsk/providers/?smartFilter=internet&sorting=POPULAR",
        # "https://dominternet.ru/novosibirsk/providers/?smartFilter=internet-mobile&sorting=POPULAR",
        # "https://dominternet.ru/novosibirsk/providers/?smartFilter=internet-tv&sorting=POPULAR",
        # "https://dominternet.ru/novosibirsk/providers/?smartFilter=internet-tv-mobile&sorting=POPULAR",
        # "https://dominternet.ru/novosibirsk/providers/?smartFilter=subscriptions&sorting=POPULAR",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/?smartFilter=subscriptions",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/internet-mobile/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/internet-tv-mobile/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/internet-tv/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/internet/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/reviews/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/tariffs/45571/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/unlimited/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/wifi/",
        # "https://dominternet.ru/novosibirsk/providers/rostelecom/with-tv/",
        # "https://dominternet.ru/novosibirsk/rating/",
        # "https://dominternet.ru/novosibirsk/reviews/",
        # "https://dominternet.ru/novosibirsk/tariffs/",
        # "https://dominternet.ru/novosibirsk/tariffs/100mbit/",
        # "https://dominternet.ru/novosibirsk/tariffs/1gbit/",
        # "https://dominternet.ru/novosibirsk/tariffs/200mbit/",
        # "https://dominternet.ru/novosibirsk/tariffs/300mbit/",
        # "https://dominternet.ru/novosibirsk/tariffs/500mbit/",
        # "https://dominternet.ru/novosibirsk/tariffs/?smartFilter=subscriptions",
        # "https://dominternet.ru/novosibirsk/tariffs/cheap/",
        # "https://dominternet.ru/novosibirsk/tariffs/fast/",
        # "https://dominternet.ru/novosibirsk/tariffs/free-connection/",
        # "https://dominternet.ru/novosibirsk/tariffs/gaming/",
        # "https://dominternet.ru/novosibirsk/tariffs/internet-mobile/",
        # "https://dominternet.ru/novosibirsk/tariffs/internet-tv-mobile/",
        # "https://dominternet.ru/novosibirsk/tariffs/internet-tv/",
        # "https://dominternet.ru/novosibirsk/tariffs/internet/",
        # "https://dominternet.ru/novosibirsk/tariffs/promo/",
        # "https://dominternet.ru/novosibirsk/tariffs/today/",
        # "https://dominternet.ru/novosibirsk/tariffs/wifi/",
        # "https://dominternet.ru/novosibirsk/tariffs/with-tv/",
        # "https://dominternet.ru/providers/rostelecom/",
        # "https://dominternet.ru/providers/rostelecom/checkaddress/",
        # "https://dominternet.ru/saratov/",
        # "https://dominternet.ru/speedtest/",
        # "https://dominternet.ru/subscriptions/",
        # "https://gigaboom.ru/",
        # "https://gigaboom.ru/articles/",
        # "https://gigaboom.ru/internet-po-adresu/",
        # "https://gigaboom.ru/internet-po-adresu/taganskij/",
        # "https://gigaboom.ru/internet-po-adresu/taganskij/ul-abelmanovskaya/",
        # "https://gigaboom.ru/internet-po-adresu/taganskij/ul-abelmanovskaya/3/",
        # "https://gigaboom.ru/office/",
        # "https://gigaboom.ru/personal-data/",
        # "https://gigaboom.ru/providers/",
        # "https://gigaboom.ru/providers/mts/",
        # "https://gigaboom.ru/providers/mts/reviews/",
        # "https://gigaboom.ru/providers/mts/sale/",
        # "https://gigaboom.ru/providers/mts/tariffs/",
        # "https://gigaboom.ru/rating/",
        # "https://gigaboom.ru/speedtest/",
        # "https://gigaboom.ru/tariffs/",
        # "https://gigaboom.ru/tariffs/besprovodnoj-internet/",
        # "https://gigaboom.ru/tariffs/bezlimitnye-tarify/",
        # "https://gigaboom.ru/tariffs/internet-1-gbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-10-mbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-100-mbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-200-mbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-300-mbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-400-mbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-50-mbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-500-mbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-800-mbit-sek/",
        # "https://gigaboom.ru/tariffs/internet-do-300-rub/",
        # "https://gigaboom.ru/tariffs/internet-do-500-rub/",
        # "https://gigaboom.ru/tariffs/internet-do-800-rub/",
        # "https://gigaboom.ru/tariffs/internet-televidenie/",
        # "https://gigaboom.ru/tariffs/mobilnyj-internet/",
        # "https://gigaboom.ru/tariffs/mts/aktsiya_tarif_1_100_mo_fttb_mesyats_v_podarok/",
        # "https://gigaboom.ru/tariffs/nedorogoj-domashnij-internet/",
        # "https://gigaboom.ru/tariffs/provodnoj-internet/",
        # "https://gigaboom.ru/tariffs/skorostnoj-internet/",
        # "https://gigaboom.ru/tariffs/televidenie/",
        # "https://gigaboom.ru/tariffs/vygodnye-tarify/",
        # "https://gigaboom.ru/tariffs/wi-fi-internet/",
        # "https://gigaboom.ru/terms-of-use/",
        # "https://internet.gde-luchshe.ru/",
        # "https://www.gde-luchshe.ru/company/",
        # "https://internet.gde-luchshe.ru/domashnij-internet/",
        # "https://internet.gde-luchshe.ru/internet-tv-mobile/",
        # "https://internet.gde-luchshe.ru/internet-mobile/",
        # "https://telecom.gde-luchshe.ru/",
        # "https://internet.gde-luchshe.ru/internet-na-dachu/",
        # "https://internet.gde-luchshe.ru/interaktivnoe-tv/",
        # "https://internet.gde-luchshe.ru/provider/",
        # "https://internet.gde-luchshe.ru/tariffs/",
        # "https://internet.gde-luchshe.ru/help/",
        # "https://kaliningrad.gde-luchshe.ru/provaidery/kaliningradskaya/volodarovka/ulitsa-lugovaya/",
        # "https://kaliningrad.gde-luchshe.ru/provider/rostelekom/"
        ]


class TestMakeScreens:
    def test_make_screenshot(driver):
        # driver.set_window_size(1920, 8300)

        for index, url in enumerate(urls):
            driver.get(url)
            site_name = names[index]
            screenshot_path = f"screenshot_{site_name}.png"
            driver.save_screenshot(screenshot_path)
            time.sleep(3)
            print(f" Не сделал вот тут {site_name}")


class TestMakeScreenss:
    def test_make_screenshot(self, driver):
        driver.set_window_size(1920, 8300)

        for url in urls:
            driver.get(url)
            site_name = url.split("/")[-2]
            screenshot_path = f"screenshot_{site_name}.png"
            driver.save_screenshot(screenshot_path)
            time.sleep(2)
