name: seo
on:
  workflow_dispatch:

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  HEADLESS: ${{ secrets.HEADLESS }}

permissions:
  contents: read
  pages: write
  id-token: write


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
             pip install openpyxl

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: tests
        # if: "github.event.inputs.deployment_target == 'all'"
        run: pytest tests/test_seo_google.py
        continue-on-error: true

      - name: Upload result files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SEO Results
          path: |
            website_results_msk.xlsx
            website_results_spb.xlsx
            website_results_ekb.xlsx
            website_results.xlsx